# Generated by Django 4.2.13 on 2026-04-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seekerprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('higher', 'Высшее'), ('incomplete_higher', 'Неоконченное высшее'), ('secondary_special', 'Средне-специальное'), ('secondary', 'Среднее')], max_length=50, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='institution',
            field=models.CharField(blank=True, choices=[('АТТК', 'АТТК (Актюбинский технико-технологический колледж)'), ('КазНУ', 'КазНУ им. аль-Фараби'), ('ЕНУ', 'ЕНУ им. Л.Н. Гумилева'), ('КБТУ', 'Казахстанско-Британский технический университет'), ('МУИТ', 'Международный университет информ. технологий'), ('АУЭС', 'Алматинский университет энергетики и связи'), ('СДУ', 'Университет им. Сулеймана Демиреля'), ('other', 'Другое учебное заведение')], max_length=100, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='Специальность / Должность'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='education',
            field=models.TextField(blank=True, verbose_name='Доп. инфо об образовании'),
        ),
    ]
