# Generated by Django 4.2.13 on 2026-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seekerprofile_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
    ]
