# Generated by Django 4.2.13 on 2026-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('viewed', 'Просмотрено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('match_score', models.PositiveIntegerField(default=0, verbose_name='Совпадение (%)')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сохранённая вакансия',
                'verbose_name_plural': 'Сохранённые вакансии',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('experience_required', models.CharField(blank=True, max_length=100, verbose_name='Опыт')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('employment_type', models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('remote', 'Удалённая работа'), ('contract', 'Контракт'), ('internship', 'Стажировка')], default='full', max_length=20, verbose_name='Тип занятости')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
