# Generated by Django 4.2.13 on 2026-04-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='experience_required',
            field=models.CharField(blank=True, choices=[('no_experience', 'Нет опыта'), ('1_3_years', 'От 1 года до 3 лет'), ('3_6_years', 'От 3 до 6 лет'), ('more_6_years', 'Более 6 лет')], max_length=20, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, choices=[('Алматы', 'Алматы'), ('Астана', 'Астана'), ('Актобе', 'Актобе'), ('Шымкент', 'Шымкент'), ('Караганда', 'Караганда'), ('Другой', 'Другой (Удаленка)')], max_length=50, verbose_name='Город'),
        ),
    ]
