# Generated by Django 4.2.13 on 2026-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_vacancy_experience_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='education_required',
            field=models.CharField(blank=True, choices=[('higher', 'Высшее'), ('incomplete_higher', 'Неоконченное высшее'), ('secondary_special', 'Средне-специальное'), ('secondary', 'Среднее')], max_length=50, verbose_name='Требуемое образование'),
        ),
    ]
